### ISSUE TITLE
Prepare CMDB and SLAM monitoring probes 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/slam#4]
Other components probes links:
https://docs.google.com/spreadsheets/d/1DXi9cqZNLVaqsOpQjG44cCfCckrRNRo2nBufbUPblJs/edit#gid=0

Probes for Infrastructure Manager - use as an example:
https://github.com/indigo-dc/im/tree/master/monitoring

**Comment by bwilk** [comment]
https://indigo-slam.cloud.ba.infn.it:8443
https://indigo-paas.cloud.ba.infn.it/cmdb

**Comment by wziajka** [comment]
Monitoring probes:
https://github.com/indigo-dc/cmdb/tree/master/tools/monitoring-probes
https://github.com/cyfronet-fid/slam/tree/master/tools/monitoring-probes

@bwilk  please fill docs, because I don't have permissions.
